// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIfJVfbCA3tAFDSWOH3j3shI4AHJxwnvc',
    appId: '1:974041121202:android:d87ec7ce99f4f5d6d6a4ab',
    messagingSenderId: '974041121202',
    projectId: 'botanica-grocery-app',
    storageBucket: 'botanica-grocery-app.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfFBKAdu3x1YTeb7MouRS4hLE6Z5eYrs8',
    appId: '1:974041121202:web:627f57d92b74f72bd6a4ab',
    messagingSenderId: '974041121202',
    projectId: 'botanica-grocery-app',
    authDomain: 'botanica-grocery-app.firebaseapp.com',
    storageBucket: 'botanica-grocery-app.firebasestorage.app',
    measurementId: 'G-2P5WJGK5CD',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQlfvNo3bEFehu1QxbuB9ymsNKqpMcT4M',
    appId: '1:974041121202:ios:1ed92a3d63177f0ad6a4ab',
    messagingSenderId: '974041121202',
    projectId: 'botanica-grocery-app',
    storageBucket: 'botanica-grocery-app.firebasestorage.app',
    iosBundleId: 'com.example.botanica',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQlfvNo3bEFehu1QxbuB9ymsNKqpMcT4M',
    appId: '1:974041121202:ios:1ed92a3d63177f0ad6a4ab',
    messagingSenderId: '974041121202',
    projectId: 'botanica-grocery-app',
    storageBucket: 'botanica-grocery-app.firebasestorage.app',
    iosBundleId: 'com.example.botanica',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfFBKAdu3x1YTeb7MouRS4hLE6Z5eYrs8',
    appId: '1:974041121202:web:bef1d1d77384912ed6a4ab',
    messagingSenderId: '974041121202',
    projectId: 'botanica-grocery-app',
    authDomain: 'botanica-grocery-app.firebaseapp.com',
    storageBucket: 'botanica-grocery-app.firebasestorage.app',
    measurementId: 'G-7J3DLK1EVM',
  );
}
